import React from 'react';
import { useLocation } from 'wouter';
import { useLanguage } from '../contexts/LanguageContext';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Streamdown } from 'streamdown';

export default function Legal() {
  const [, setLocation] = useLocation();
  const { language, t } = useLanguage();

  const contentZh = `
# Meta-Lingo 软件使用许可协议（非商业）

Copyright © 2026 Tommy Leo
All rights reserved.

Meta-Lingo 软件（以下简称“软件”）为著作权人 Tommy Leo 独立开发完成的计算机软件作品，系一款面向语言学与话语研究的语料库研究软件，主要用于文本数据的分析、研究与学术探索，受《中华人民共和国著作权法》及相关法律法规保护。

在您下载、安装、运行或以其他方式使用本软件之前，请仔细阅读并充分理解本许可协议的全部内容。一旦使用本软件，即视为您已阅读、理解并同意接受本协议全部条款的约束。

## 一、授权范围

在遵守本协议全部条款的前提下，著作权人授予用户一项非排他性、不可转让、不可再许可的有限使用许可，仅限于以下用途：

1. 个人学习；
2. 学术研究；
3. 与语料库分析、语言研究或相关研究活动直接相关的其他非商业目的使用。

## 二、明确禁止的行为

除法律另有强制性规定外，未经著作权人事先书面许可，用户不得从事包括但不限于以下行为：

1. 对 Meta-Lingo 软件进行反编译、反汇编、反向工程，或以任何形式试图获取本软件的源代码；
2. 对 Meta-Lingo 软件进行修改、改编、拆分、二次开发，或基于本软件制作衍生作品；
3. 以任何形式对 Meta-Lingo 软件进行再次分发、转售、出租、出借、共享、捆绑传播或提供下载；
4. 将 Meta-Lingo 软件用于任何直接或间接的商业目的，包括但不限于收费服务、培训课程、商业产品集成、企业或机构内部使用；
5. 移除、隐藏、篡改 Meta-Lingo 软件中包含的任何版权声明、作者信息或本许可协议内容。

## 三、权利保留

除本协议明确授予用户的使用权外，Meta-Lingo 软件的全部权利（包括但不限于著作权、修改权、复制权、发行权、信息网络传播权等）均由著作权人 Tommy Leo 保留。本协议不构成任何形式的权利转让或权利放弃。

## 四、免责声明

Meta-Lingo 软件按“现状（AS IS）”提供。在适用法律允许的最大范围内，著作权人不对本软件的适用性、准确性、完整性、可靠性或研究结果作出任何明示或默示的保证。

用户因使用或无法使用 Meta-Lingo 软件而产生的任何直接或间接损失，著作权人在法律允许的范围内不承担任何责任。

## 五、违约责任

如用户违反本协议任何条款，著作权人有权依法要求用户立即停止侵权行为，并保留追究其法律责任的权利，包括但不限于要求赔偿损失、消除影响等。

## 六、适用法律与争议解决

本协议的订立、效力、解释、履行及争议解决均适用中华人民共和国法律。

因本协议引起的或与本协议有关的任何争议，双方应首先友好协商解决；协商不成的，任何一方均可向著作权人所在地有管辖权的人民法院提起诉讼。

## 七、协议生效

本协议自用户下载、安装、运行或以其他方式使用 Meta-Lingo 软件之日起生效。
`;

  const contentEn = `
# META-LINGO SOFTWARE LICENSE AGREEMENT (NON-COMMERCIAL)

Copyright © 2026 Tommy Leo
All rights reserved.

Meta-Lingo (the “Software”) is a copyrighted software independently developed by Tommy Leo. It is a corpus-based research tool designed for linguistic, discourse, and text analysis research, and is protected by applicable copyright laws and regulations.

PLEASE READ THIS LICENSE AGREEMENT CAREFULLY BEFORE USING THE SOFTWARE. BY DOWNLOADING, INSTALLING, RUNNING, OR OTHERWISE USING META-LINGO, YOU AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT.

In case of any inconsistency between the Chinese and English versions of this Agreement, the Chinese version shall prevail.

## 1. License Grant

Subject to full compliance with this Agreement, the author grants you a limited, non-exclusive, non-transferable, and non-sublicensable license to use Meta-Lingo solely for:

- Personal learning purposes;
- Academic or research purposes;
- Other non-commercial uses directly related to corpus analysis or linguistic research.

## 2. Prohibited Activities

Unless expressly permitted by applicable law or authorized in writing by the author, you shall not:

1. Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of Meta-Lingo;
2. Modify, adapt, translate, alter, or create derivative works based on Meta-Lingo;
3. Redistribute, resell, rent, lease, lend, sublicense, or otherwise make Meta-Lingo available to any third party in any form;
4. Use Meta-Lingo for any commercial purpose, whether direct or indirect, including but not limited to paid services, training programs, commercial products, or internal use by enterprises or organizations;
5. Remove, obscure, or alter any copyright notices, author attributions, or license terms included in Meta-Lingo.

## 3. Reservation of Rights

All rights not expressly granted to you under this Agreement are reserved by the author, Tommy Leo. This Agreement does not constitute any transfer or waiver of intellectual property rights.

## 4. Disclaimer

META-LINGO IS PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE AUTHOR DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THE AUTHOR DOES NOT GUARANTEE THE ACCURACY OR RELIABILITY OF ANY RESEARCH RESULTS GENERATED BY THE SOFTWARE.

## 5. Breach and Liability

Any breach of this Agreement may result in immediate termination of your license. The author reserves the right to pursue all legal remedies available under applicable law for any violation of this Agreement.

## 6. Governing Law and Jurisdiction

This Agreement shall be governed by and construed in accordance with the laws of the People’s Republic of China.

Any dispute arising out of or relating to this Agreement shall be submitted to the competent court with jurisdiction at the author’s place of residence.

## 7. Effective Date

This Agreement shall become effective upon your downloading, installing, running, or otherwise using Meta-Lingo.
`;

  return (
    <div className="min-h-screen bg-[#F7F7F6]">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#F7F7F6]/80 backdrop-blur-md border-b border-gray-200">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => setLocation('/')}>
            <img src="/images/logo-icon.png" alt="Meta-Lingo" className="w-8 h-8" />
            <span className="text-xl font-bold text-gray-900">Meta-Lingo</span>
          </div>
          <Button 
            variant="ghost" 
            onClick={() => setLocation('/')}
            className="flex items-center gap-2 hover:bg-gray-100"
          >
            <ArrowLeft className="w-4 h-4" />
            {t('detail.back')}
          </Button>
        </div>
      </nav>

      <main className="pt-24 pb-16 container mx-auto px-4">
        <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm border border-gray-200 p-8 md:p-12 prose prose-lg max-w-none prose-headings:text-gray-900 prose-p:text-gray-600">
          <Streamdown>{language === 'zh' ? contentZh : contentEn}</Streamdown>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-[#F7F7F6] border-t border-gray-200 py-12 mt-12">
        <div className="container mx-auto px-4 text-center text-gray-500">
          <div className="flex items-center justify-center gap-2 mb-4 opacity-50">
            <img src="/images/logo-icon.png" alt="Meta-Lingo" className="w-6 h-6 grayscale" />
            <span className="font-semibold">Meta-Lingo</span>
          </div>
          <p>{t('footer.copyright')}</p>
        </div>
      </footer>
    </div>
  );
}
